import React from 'react'
import './EcoSystem.css'

export default function EcoSystem() {
    return (
        <div>
            <section class="Ecosystem_bg_here  elementor-section elementor-top-section elementor-element elementor-element-455f1a6 elementor-section-full_width banner-position-sec elementor-section-height-default elementor-section-height-default"  id='Ecosystem'>
                <div class="elementor-container elementor-column-gap-default">
                    <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-67f8556" data-id="67f8556" data-element_type="column">
                        <div class="elementor-widget-wrap elementor-element-populated">
                            <div class="elementor-element elementor-element-bd93d78 elementor-widget elementor-widget-heading" data-id="bd93d78" data-element_type="widget" data-widget_type="heading.default">
                                <div class="elementor-widget-container">
                                    <h2 class="elementor-heading-title elementor-size-default">
                                        <div class="main-heading">
                                            <h2 className='text-center mt-5 text_bg_her_ecosystem'>OUR ECOSYSTEM</h2>
                                        </div>
                                    </h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="elementor-section elementor-top-section elementor-element elementor-element-26877e2 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="26877e2" data-element_type="section">
                <div class="elementor-container elementor-column-gap-default container">
                    <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-0ca05f0" data-id="0ca05f0" data-element_type="column">
                        <div class="elementor-widget-wrap elementor-element-populated">
                            <section class=" elementor-section elementor-inner-section elementor-element elementor-element-975bad7 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="975bad7" data-element_type="section">
                                <div class=" row elementor-container elementor-column-gap-default mt-5">

                                    <div class="col-lg-6 col-md-6 elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-9dc80bf" data-id="9dc80bf" data-element_type="column">
                                        <div class="elementor-widget-container col_ecosystem_second">
                                            <img width="2048" height="1748" src="https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic.png" class="attachment-full size-full" alt="" loading="lazy" srcset="https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic.png 2048w, https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic-300x256.png 300w, https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic-1024x874.png 1024w, https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic-768x656.png 768w, https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic-1536x1311.png 1536w, https://evergrowcoin.com/wp-content/uploads/2021/12/EcoSystem-Pic-1568x1338.png 1568w" style={{ width: "80%", height: "85.35%", maxWidth: "2048px" }} />
                                        </div>

                                    </div>
                                    <div class=" col-lg-6 col-md-6  elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-b8eded4" data-id="b8eded4" data-element_type="column">

                                        <div class="elementor-widget-container ">
                                            <p class="text-white text_ecosystem_p">Property Investment  Coin has revolutionised the world of crypto by introducing the first Ecosystem of its kind designed to align 100% with investors.
                                                100% of all profits generated by our Ecosystem of cutting-edge utilities will be used to Buy Back &amp; Burn $EGC.
                                                This will result in more $BUSD rewards, more positive price action, and less total circulating supply eligible to receive rewards.</p>
                                        </div>

                                    </div>
                                    <img src="https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1024x712.png" class="attachment-large size-large swap_img_resposive" alt="" loading="lazy" srcset="https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1024x712.png 1024w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-300x209.png 300w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-768x534.png 768w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1536x1069.png 1536w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1568x1091.png 1568w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows.png 2031w" style={{ width: "100%", height: "100%", maxWidth: "2031px" }} />


                                </div>
                            </section>
                            <section class="text_section_img elementor-section elementor-inner-section elementor-element elementor-element-94f40b2 elementor-section-content-middle eco-sys-bottom-sec elementor-reverse-mobile elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="94f40b2" data-element_type="section">
                                <div class="elementor-container elementor-column-gap-default">

                                    <div class="elementor-column elementor-col-25 elementor-inner-column elementor-element elementor-element-19129da" data-id="19129da" data-element_type="column">
                                        <div class="elementor-widget-wrap elementor-element-populated">
                                            <div class="elementor-element elementor-element-e943c4c daap-sec elementor-widget elementor-widget-text-editor" data-id="e943c4c" data-element_type="widget" data-widget_type="text-editor.default">
                                                <div class="elementor-widget-container">
                                                    <div class="about-us section">
                                                        <div class="container">
                                                            <div class="about-position-image postion_here_line ">
                                                                <img src="https://evergrowcoin.com/wp-content/uploads/2021/12/Plaque_Left.png" />
                                                            </div>
                                                            <div className="row">
                                                                <div class="conent col-lg-6 col-md-6">
                                                                    <div class="main-heading dapp_swapheading">
                                                                        <h2 className='fs-1 fw-700 Swap_heading'>dApp and Swap Exchange</h2>
                                                                    </div>
                                                                    <p class="Swap_text mt-5">With constant updates and community involvement, our dApp Dashboard consists of Swap exchange with a user-friendly interface and allows holders to view rewards generated in real-time.
                                                                        Our Ecosystem lends itself to endless potential, all made possible by our team, which is the perfect mix of brain and brawn, to make the experience a personal one for every investor.</p>
                                                                </div>
                                                                <div className="img_arrow col-lg-6 col-md-6 dapp_swapheading" >
                                                                    <img src="https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1024x712.png" class="attachment-large size-large swap_inlarge_here" alt="" loading="lazy" srcset="https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1024x712.png 1024w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-300x209.png 300w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-768x534.png 768w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1536x1069.png 1536w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows-1568x1091.png 1568w, https://evergrowcoin.com/wp-content/uploads/2021/12/Arrows.png 2031w" style={{ width: "100%", height: "100%", maxWidth: "2031px" }} />

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </section>
                            <div class="elementor-element elementor-element-8debe35 elementor-widget elementor-widget-text-editor" data-id="8debe35" data-element_type="widget" data-widget_type="text-editor.default">
                                <div class="elementor-widget-container">
                                    <div class="bold-btn-link">
                                        <a href="/" target="_blank" rel="noopener">DAPP </a>
                                        <a href="#" target="_blank" rel="noopener">SWAP</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


        </div>
    )
}
